### ISSUE TITLE
Get large scale feedback

### ISSUE THREAD

**Issue by saulshanabrook** [saulshanabrook/search-in-clojure#1]
I should get some feedback on the basic premises/design principles that this system is built on. 

Before/alongside that I need to:
1. Add docs to readme explaining methodology
2. Add GP algorithm

**Comment by saulshanabrook** [comment]
@Vaguery are you around this weekend to chat about this?
(/are you interested)

**Comment by Vaguery** [comment]
I am, and I am. Actually I have a chat with @nicmcphee about my own general-purpose search framework this afternoon. If we can trust Hangouts, we could do something all at once. Otherwise I can chat this evening, say 7ish?

**Comment by saulshanabrook** [comment]
@Vaguery Yeah I saw you were making something with a similar objective. I thought it would be best to see how both of our strategies pan out and then compare/contrast. Would tomorrow afternoon work? Sometime after 4pm?

**Comment by Vaguery** [comment]
Moving this to Twitter. Also I sent you a Slack invite.
